### PR TITLE
Add test on clicking color picker selection

### PR DESCRIPTION
**Pull request by abiyasa**
I thought about adding a simple example on how to test widget behaviour, on top of testing the rendering result. This is a simple implementation which shows:

- how to get an component instance from marko-devtools' `context.render` result.
- how to simulate click event

I was wondering if we can use sinon for mocking/spying & make the code much nicer. I made another branch with sinon's spy: https://github.com/abiyasa/marko-color-picker/commit/b4e9c7c6f38fe17e1c450a5cae41dc9152d24139

What do you think?

### CODE REVIEW

**Comment by austinkelleher** [comment]
@abiyasa Thanks for adding this! I purposely did not add tests to all of the components to keep the tutorial simple. It's okay to add the test, but I'd rather have the README contain only one test example. I think we should leave out `sinon`as well to keep it as simple as possible although I think it would be better to use in practice.

Maybe we should replace the test example in the README with your example since it showcases several features that can be used inside of the tests that you would expect like `click` and event emitters. What do you think?

**Comment by abiyasa** [comment]
Agree with you with leaving out sinon for simplicity.

> Maybe we should replace the test example in the README with your example since it showcases several features that can be used inside of the tests that you would expect like click and event emitters.

Sure! Although adding this on top of the existing example on readme also fine, imo.

**Comment by austinkelleher** [comment]
@abiyasa Feel free to add both examples in the README to this PR. Thanks!

**Comment by austinkelleher** [comment]
@abiyasa Actually I'll go ahead and merge this, add the example to the README, and publish a new version of the website, so we can get this out today. Thanks again for your help on this!

**Comment by abiyasa** [comment]
Thanks for merging this! Sorry for late response, it's already weekend here in Berlin ;-)

**Pull request merged**
